var wms_layers = [];


        var lyr_OSMStandard_0 = new ol.layer.Tile({
            'title': 'OSM Standard',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' &middot; <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors, CC-BY-SA</a>',
                url: 'http://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format__1 = new ol.format.GeoJSON();
var features__1 = format__1.readFeatures(json__1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource__1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource__1.addFeatures(features__1);
var lyr__1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource__1, 
                style: style__1,
                interactive: true,
    title: 'היתר בנייה של אנטנה<br />\
    <img src="styles/legend/_1_0.png" /> אין היתר<br />\
    <img src="styles/legend/_1_1.png" /> יש היתר<br />'
        });
var format__2 = new ol.format.GeoJSON();
var features__2 = format__2.readFeatures(json__2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource__2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource__2.addFeatures(features__2);
var lyr__2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource__2, 
                style: style__2,
                interactive: true,
    title: 'אנטנות על פי חברות סלולר<br />\
    <img src="styles/legend/_2_0.png" /> גולן תקשורת<br />\
    <img src="styles/legend/_2_1.png" /> סלקום<br />\
    <img src="styles/legend/_2_2.png" /> פלאפון<br />\
    <img src="styles/legend/_2_3.png" /> PHI (משרת את הוט ופרטנר)<br />'
        });
var format__3 = new ol.format.GeoJSON();
var features__3 = format__3.readFeatures(json__3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource__3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource__3.addFeatures(features__3);
var lyr__3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource__3, 
                style: style__3,
                interactive: true,
    title: 'אנטנות על פי ערים<br />\
    <img src="styles/legend/_3_0.png" /> אבן יהודה<br />\
    <img src="styles/legend/_3_1.png" /> אור יהודה<br />\
    <img src="styles/legend/_3_2.png" /> אור עקיבא<br />\
    <img src="styles/legend/_3_3.png" /> אושה<br />\
    <img src="styles/legend/_3_4.png" /> אזור<br />\
    <img src="styles/legend/_3_5.png" /> אחוזם<br />\
    <img src="styles/legend/_3_6.png" /> אחיהוד<br />\
    <img src="styles/legend/_3_7.png" /> אחיטוב<br />\
    <img src="styles/legend/_3_8.png" /> אחיסמך<br />\
    <img src="styles/legend/_3_9.png" /> אחיעזר<br />\
    <img src="styles/legend/_3_10.png" /> איבים<br />\
    <img src="styles/legend/_3_11.png" /> אייל<br />\
    <img src="styles/legend/_3_12.png" /> איילת השחר<br />\
    <img src="styles/legend/_3_13.png" /> איכסאל<br />\
    <img src="styles/legend/_3_14.png" /> איל<br />\
    <img src="styles/legend/_3_15.png" /> אילון<br />\
    <img src="styles/legend/_3_16.png" /> אילות<br />\
    <img src="styles/legend/_3_17.png" /> אילניה<br />\
    <img src="styles/legend/_3_18.png" /> אילת<br />\
    <img src="styles/legend/_3_19.png" /> אילת השחר<br />\
    <img src="styles/legend/_3_20.png" /> איתמר<br />\
    <img src="styles/legend/_3_21.png" /> איתן<br />\
    <img src="styles/legend/_3_22.png" /> אכסאל<br />\
    <img src="styles/legend/_3_23.png" /> אל-עזי<br />\
    <img src="styles/legend/_3_24.png" /> אל-רום<br />\
    <img src="styles/legend/_3_25.png" /> אלון<br />\
    <img src="styles/legend/_3_26.png" /> אלון הגליל<br />\
    <img src="styles/legend/_3_27.png" /> אלון מורה<br />\
    <img src="styles/legend/_3_28.png" /> אלון שבות<br />\
    <img src="styles/legend/_3_29.png" /> אלון תבור<br />\
    <img src="styles/legend/_3_30.png" /> אלוני הבשן<br />\
    <img src="styles/legend/_3_31.png" /> אלונים<br />\
    <img src="styles/legend/_3_32.png" /> אליכין<br />\
    <img src="styles/legend/_3_33.png" /> אליעד<br />\
    <img src="styles/legend/_3_34.png" /> אליפז<br />\
    <img src="styles/legend/_3_35.png" /> אליפלט<br />\
    <img src="styles/legend/_3_36.png" /> אליקים<br />\
    <img src="styles/legend/_3_37.png" /> אלישיב<br />\
    <img src="styles/legend/_3_38.png" /> אלישמע<br />\
    <img src="styles/legend/_3_39.png" /> אלמגור<br />\
    <img src="styles/legend/_3_40.png" /> אלעד<br />\
    <img src="styles/legend/_3_41.png" /> אלפי מנשה<br />\
    <img src="styles/legend/_3_42.png" /> אלקנה<br />\
    <img src="styles/legend/_3_43.png" /> אלרום<br />\
    <img src="styles/legend/_3_44.png" /> אמנון<br />\
    <img src="styles/legend/_3_45.png" /> אמציה<br />\
    <img src="styles/legend/_3_46.png" /> אספר<br />\
    <img src="styles/legend/_3_47.png" /> אעבלין<br />\
    <img src="styles/legend/_3_48.png" /> אפיק<br />\
    <img src="styles/legend/_3_49.png" /> אפק<br />\
    <img src="styles/legend/_3_50.png" /> אפרת<br />\
    <img src="styles/legend/_3_51.png" /> אקה אל ג`בייה<br />\
    <img src="styles/legend/_3_52.png" /> ארגמן<br />\
    <img src="styles/legend/_3_53.png" /> ארסוף<br />\
    <img src="styles/legend/_3_54.png" /> אשבול<br />\
    <img src="styles/legend/_3_55.png" /> אשדוד<br />\
    <img src="styles/legend/_3_56.png" /> אשדות יעקב  מאוחד<br />\
    <img src="styles/legend/_3_57.png" /> אשכול<br />\
    <img src="styles/legend/_3_58.png" /> אשלים<br />\
    <img src="styles/legend/_3_59.png" /> אשקלון<br />\
    <img src="styles/legend/_3_60.png" /> אשתאול<br />\
    <img src="styles/legend/_3_61.png" /> אתר דרך<br />\
    <img src="styles/legend/_3_62.png" /> באקה אל גרביה<br />\
    <img src="styles/legend/_3_63.png" /> באקה אל-גרביה<br />\
    <img src="styles/legend/_3_64.png" /> באר אורה<br />\
    <img src="styles/legend/_3_65.png" /> באר טוביה<br />\
    <img src="styles/legend/_3_66.png" /> באר יעקב<br />\
    <img src="styles/legend/_3_67.png" /> באר שבע<br />\
    <img src="styles/legend/_3_68.png" /> בארות יצחק<br />\
    <img src="styles/legend/_3_69.png" /> בארותיים<br />\
    <img src="styles/legend/_3_70.png" /> בארי<br />\
    <img src="styles/legend/_3_71.png" /> בואינה נוגידאת<br />\
    <img src="styles/legend/_3_72.png" /> בועיינה-נוג`ידאת<br />\
    <img src="styles/legend/_3_73.png" /> בועיינהנוג`ידאת<br />\
    <img src="styles/legend/_3_74.png" /> בוקעאתא<br />\
    <img src="styles/legend/_3_75.png" /> בוקעתא<br />\
    <img src="styles/legend/_3_76.png" /> בחן<br />\
    <img src="styles/legend/_3_77.png" /> ביאדה<br />\
    <img src="styles/legend/_3_78.png" /> בילו<br />\
    <img src="styles/legend/_3_79.png" /> ביר אל מכסור<br />\
    <img src="styles/legend/_3_80.png" /> ביר אלמכסור<br />\
    <img src="styles/legend/_3_81.png" /> בית אורן<br />\
    <img src="styles/legend/_3_82.png" /> בית אל<br />\
    <img src="styles/legend/_3_83.png" /> בית אלפא<br />\
    <img src="styles/legend/_3_84.png" /> בית ברל<br />\
    <img src="styles/legend/_3_85.png" /> בית ג`אן<br />\
    <img src="styles/legend/_3_86.png" /> בית ג`ן<br />\
    <img src="styles/legend/_3_87.png" /> בית גאן<br />\
    <img src="styles/legend/_3_88.png" /> בית גמליאל<br />\
    <img src="styles/legend/_3_89.png" /> בית דגן<br />\
    <img src="styles/legend/_3_90.png" /> בית הלל<br />\
    <img src="styles/legend/_3_91.png" /> בית העמק<br />\
    <img src="styles/legend/_3_92.png" /> בית זית<br />\
    <img src="styles/legend/_3_93.png" /> בית זרע<br />\
    <img src="styles/legend/_3_94.png" /> בית חורון<br />\
    <img src="styles/legend/_3_95.png" /> בית חירות<br />\
    <img src="styles/legend/_3_96.png" /> בית חלקיה<br />\
    <img src="styles/legend/_3_97.png" /> בית חנניה<br />\
    <img src="styles/legend/_3_98.png" /> בית חרות<br />\
    <img src="styles/legend/_3_99.png" /> בית יהושע<br />\
    <img src="styles/legend/_3_100.png" /> בית יוסף<br />\
    <img src="styles/legend/_3_101.png" /> בית ינאי<br />\
    <img src="styles/legend/_3_102.png" /> בית יצחק<br />\
    <img src="styles/legend/_3_103.png" /> בית יצחק שער חפר<br />\
    <img src="styles/legend/_3_104.png" /> בית יצחק-שער חפר<br />\
    <img src="styles/legend/_3_105.png" /> בית ליד<br />\
    <img src="styles/legend/_3_106.png" /> בית מאיר<br />\
    <img src="styles/legend/_3_107.png" /> בית נחמיה<br />\
    <img src="styles/legend/_3_108.png" /> בית ניר<br />\
    <img src="styles/legend/_3_109.png" /> בית נקופה<br />\
    <img src="styles/legend/_3_110.png" /> בית עובד<br />\
    <img src="styles/legend/_3_111.png" /> בית עוזיאל<br />\
    <img src="styles/legend/_3_112.png" /> בית עריף<br />\
    <img src="styles/legend/_3_113.png" /> בית קשת<br />\
    <img src="styles/legend/_3_114.png" /> בית שאן<br />\
    <img src="styles/legend/_3_115.png" /> בית``ר עילית<br />\
    <img src="styles/legend/_3_116.png" /> ביתן אהרון<br />\
    <img src="styles/legend/_3_117.png" /> ביתן אהרן<br />\
    <img src="styles/legend/_3_118.png" /> ביתר עילית<br />\
    <img src="styles/legend/_3_119.png" /> בן זכאי<br />\
    <img src="styles/legend/_3_120.png" /> בן שמן<br />\
    <img src="styles/legend/_3_121.png" /> בני דרום<br />\
    <img src="styles/legend/_3_122.png" /> בני דרור<br />\
    <img src="styles/legend/_3_123.png" /> בני עי"ש<br />\
    <img src="styles/legend/_3_124.png" /> בני עיש<br />\
    <img src="styles/legend/_3_125.png" /> בני ראם<br />\
    <img src="styles/legend/_3_126.png" /> בניה<br />\
    <img src="styles/legend/_3_127.png" /> בנימינה<br />\
    <img src="styles/legend/_3_128.png" /> בסמ"ה<br />\
    <img src="styles/legend/_3_129.png" /> בסמת טבעון<br />\
    <img src="styles/legend/_3_130.png" /> בצרה<br />\
    <img src="styles/legend/_3_131.png" /> בקה אל גרביה<br />\
    <img src="styles/legend/_3_132.png" /> בקעת בית שאן<br />\
    <img src="styles/legend/_3_133.png" /> ברורים<br />\
    <img src="styles/legend/_3_134.png" /> ברטעה<br />\
    <img src="styles/legend/_3_135.png" /> ברעם<br />\
    <img src="styles/legend/_3_136.png" /> ברקאי<br />\
    <img src="styles/legend/_3_137.png" /> ברקן<br />\
    <img src="styles/legend/_3_138.png" /> ברקת<br />\
    <img src="styles/legend/_3_139.png" /> בת חפר<br />\
    <img src="styles/legend/_3_140.png" /> בת חצור<br />\
    <img src="styles/legend/_3_141.png" /> בת ים<br />\
    <img src="styles/legend/_3_142.png" /> בת שלמה<br />\
    <img src="styles/legend/_3_143.png" /> ג`דיידה-מכר<br />\
    <img src="styles/legend/_3_144.png" /> ג`ודיידה מכר<br />\
    <img src="styles/legend/_3_145.png" /> ג`ולס<br />\
    <img src="styles/legend/_3_146.png" /> ג`לג`וליה<br />\
    <img src="styles/legend/_3_147.png" /> ג`ת<br />\
    <img src="styles/legend/_3_148.png" /> גאולים<br />\
    <img src="styles/legend/_3_149.png" /> גאליה<br />\
    <img src="styles/legend/_3_150.png" /> גבולות<br />\
    <img src="styles/legend/_3_151.png" /> גבע<br />\
    <img src="styles/legend/_3_152.png" /> גבע בנימין<br />\
    <img src="styles/legend/_3_153.png" /> גבעה<br />\
    <img src="styles/legend/_3_154.png" /> גבעות<br />\
    <img src="styles/legend/_3_155.png" /> גבעת אבני<br />\
    <img src="styles/legend/_3_156.png" /> גבעת אלה<br />\
    <img src="styles/legend/_3_157.png" /> גבעת ברנר<br />\
    <img src="styles/legend/_3_158.png" /> גבעת השלושה<br />\
    <img src="styles/legend/_3_159.png" /> גבעת זאב<br />\
    <img src="styles/legend/_3_160.png" /> גבעת ח"ן<br />\
    <img src="styles/legend/_3_161.png" /> גבעת ח``ן<br />\
    <img src="styles/legend/_3_162.png" /> גבעת חיים<br />\
    <img src="styles/legend/_3_163.png" /> גבעת חיים (מאוחד)<br />\
    <img src="styles/legend/_3_164.png" /> גבעת חיים איחוד<br />\
    <img src="styles/legend/_3_165.png" /> גבעת חיים מאוחד<br />\
    <img src="styles/legend/_3_166.png" /> גבעת יואב<br />\
    <img src="styles/legend/_3_167.png" /> גבעת יערים<br />\
    <img src="styles/legend/_3_168.png" /> גבעת ישעיהו<br />\
    <img src="styles/legend/_3_169.png" /> גבעת כ``ח<br />\
    <img src="styles/legend/_3_170.png" /> גבעת כח<br />\
    <img src="styles/legend/_3_171.png" /> גבעת ניל"י<br />\
    <img src="styles/legend/_3_172.png" /> גבעת ניל``י<br />\
    <img src="styles/legend/_3_173.png" /> גבעת נילי<br />\
    <img src="styles/legend/_3_174.png" /> גבעת עדה<br />\
    <img src="styles/legend/_3_175.png" /> גבעת עוז<br />\
    <img src="styles/legend/_3_176.png" /> גבעת שמואל<br />\
    <img src="styles/legend/_3_177.png" /> אשכולות<br />\
    <img src="styles/legend/_3_178.png" /> אשדות יעקב איחוד<br />\
    <img src="styles/legend/_3_179.png" /> אשדות יעקב  (מאוחד)<br />\
    <img src="styles/legend/_3_180.png" /> אשבל<br />\
    <img src="styles/legend/_3_181.png" /> אריאל<br />\
    <img src="styles/legend/_3_182.png" /> ארבל<br />\
    <img src="styles/legend/_3_183.png" /> אפרתה<br />\
    <img src="styles/legend/_3_184.png" /> אפיקים<br />\
    <img src="styles/legend/_3_185.png" /> אעצם<br />\
    <img src="styles/legend/_3_186.png" /> אניעם<br />\
    <img src="styles/legend/_3_187.png" /> אמץ<br />\
    <img src="styles/legend/_3_188.png" /> אמונים<br />\
    <img src="styles/legend/_3_189.png" /> אלקוש<br />\
    <img src="styles/legend/_3_190.png" /> בית חנן<br />\
    <img src="styles/legend/_3_191.png" /> בית חגי<br />\
    <img src="styles/legend/_3_192.png" /> בית הערבה<br />\
    <img src="styles/legend/_3_193.png" /> בית הגדי<br />\
    <img src="styles/legend/_3_194.png" /> בית גוברין<br />\
    <img src="styles/legend/_3_195.png" /> בית ג`וברין<br />\
    <img src="styles/legend/_3_196.png" /> בית אריה<br />\
    <img src="styles/legend/_3_197.png" /> בית אלעזרי<br />\
    <img src="styles/legend/_3_198.png" /> בירנית<br />\
    <img src="styles/legend/_3_199.png" /> ביר אל-מכסור<br />\
    <img src="styles/legend/_3_200.png" /> ביצרון<br />\
    <img src="styles/legend/_3_201.png" /> ברכה<br />\
    <img src="styles/legend/_3_202.png" /> ברוש<br />\
    <img src="styles/legend/_3_203.png" /> בקעות<br />\
    <img src="styles/legend/_3_204.png" /> בצת<br />\
    <img src="styles/legend/_3_205.png" /> בענה<br />\
    <img src="styles/legend/_3_206.png" /> בסמה<br />\
    <img src="styles/legend/_3_207.png" /> בנימינה-גבעת עדה<br />\
    <img src="styles/legend/_3_208.png" /> בני שמעון<br />\
    <img src="styles/legend/_3_209.png" /> בני ציון<br />\
    <img src="styles/legend/_3_210.png" /> בני עי``ש<br />\
    <img src="styles/legend/_3_211.png" /> בני עטרות<br />\
    <img src="styles/legend/_3_212.png" /> בני ברק<br />\
    <img src="styles/legend/_3_213.png" /> בית שמש<br />\
    <img src="styles/legend/_3_214.png" /> בית רימון<br />\
    <img src="styles/legend/_3_215.png" /> בית קמה<br />\
    <img src="styles/legend/_3_216.png" /> בית עזרא<br />\
    <img src="styles/legend/_3_217.png" /> גינתון<br />\
    <img src="styles/legend/_3_218.png" /> גיניגר<br />\
    <img src="styles/legend/_3_219.png" /> גינוסר<br />\
    <img src="styles/legend/_3_220.png" /> גילון<br />\
    <img src="styles/legend/_3_221.png" /> גיאה<br />\
    <img src="styles/legend/_3_222.png" /> גונן<br />\
    <img src="styles/legend/_3_223.png" /> גבעתיים<br />\
    <img src="styles/legend/_3_224.png" /> גולן<br />\
    <img src="styles/legend/_3_225.png" /> גלעד (אבן יצחק)<br />\
    <img src="styles/legend/_3_226.png" /> גן השומרון<br />\
    <img src="styles/legend/_3_227.png" /> גן יבנה<br />\
    <img src="styles/legend/_3_228.png" /> גן נר<br />\
    <img src="styles/legend/_3_229.png" /> גן רווה<br />\
    <img src="styles/legend/_3_230.png" /> גן שורק<br />\
    <img src="styles/legend/_3_231.png" /> גן שמואל<br />\
    <img src="styles/legend/_3_232.png" /> גנות<br />\
    <img src="styles/legend/_3_233.png" /> גנות הדר<br />\
    <img src="styles/legend/_3_234.png" /> גני יהודה<br />\
    <img src="styles/legend/_3_235.png" /> גני יוחנן<br />\
    <img src="styles/legend/_3_236.png" /> גני עם<br />\
    <img src="styles/legend/_3_237.png" /> גני תקוה<br />\
    <img src="styles/legend/_3_238.png" /> גני תקווה<br />\
    <img src="styles/legend/_3_239.png" /> גניגר<br />\
    <img src="styles/legend/_3_240.png" /> געש<br />\
    <img src="styles/legend/_3_241.png" /> געתון<br />\
    <img src="styles/legend/_3_242.png" /> גפן<br />\
    <img src="styles/legend/_3_243.png" /> גרופית<br />\
    <img src="styles/legend/_3_244.png" /> גשור<br />\
    <img src="styles/legend/_3_245.png" /> גשר<br />\
    <img src="styles/legend/_3_246.png" /> גשר הזיו<br />\
    <img src="styles/legend/_3_247.png" /> גת<br />\
    <img src="styles/legend/_3_248.png" /> דאלית אל כרמל<br />\
    <img src="styles/legend/_3_249.png" /> דאלית אל-כרמל<br />\
    <img src="styles/legend/_3_250.png" /> דאלית אלכרמל<br />\
    <img src="styles/legend/_3_251.png" /> דבורה<br />\
    <img src="styles/legend/_3_252.png" /> דבוריה<br />\
    <img src="styles/legend/_3_253.png" /> דבירה<br />\
    <img src="styles/legend/_3_254.png" /> דברת<br />\
    <img src="styles/legend/_3_255.png" /> דגניה א`<br />\
    <img src="styles/legend/_3_256.png" /> דגניה ב`<br />\
    <img src="styles/legend/_3_257.png" /> דולב<br />\
    <img src="styles/legend/_3_258.png" /> דורות<br />\
    <img src="styles/legend/_3_259.png" /> דייר חנא<br />\
    <img src="styles/legend/_3_260.png" /> דימונה<br />\
    <img src="styles/legend/_3_261.png" /> דיר אל אסד<br />\
    <img src="styles/legend/_3_262.png" /> דיר אל-אסד<br />\
    <img src="styles/legend/_3_263.png" /> דיר אלאסד<br />\
    <img src="styles/legend/_3_264.png" /> דיר חנא<br />\
    <img src="styles/legend/_3_265.png" /> דישון<br />\
    <img src="styles/legend/_3_266.png" /> דליה<br />\
    <img src="styles/legend/_3_267.png" /> דלית אל כרמל<br />\
    <img src="styles/legend/_3_268.png" /> דלתון<br />\
    <img src="styles/legend/_3_269.png" /> דן<br />\
    <img src="styles/legend/_3_270.png" /> דרום השרון<br />\
    <img src="styles/legend/_3_271.png" /> הבונים<br />\
    <img src="styles/legend/_3_272.png" /> הגושרים<br />\
    <img src="styles/legend/_3_273.png" /> הוד השרון<br />\
    <img src="styles/legend/_3_274.png" /> הזורע<br />\
    <img src="styles/legend/_3_275.png" /> היוגב<br />\
    <img src="styles/legend/_3_276.png" /> הסוללים<br />\
    <img src="styles/legend/_3_277.png" /> הר אדר<br />\
    <img src="styles/legend/_3_278.png" /> הרצליה<br />\
    <img src="styles/legend/_3_279.png" /> ורד יריחו<br />\
    <img src="styles/legend/_3_280.png" /> זוהר<br />\
    <img src="styles/legend/_3_281.png" /> זיקים<br />\
    <img src="styles/legend/_3_282.png" /> זיתן<br />\
    <img src="styles/legend/_3_283.png" /> זכרון יעקב<br />\
    <img src="styles/legend/_3_284.png" /> זכריה<br />\
    <img src="styles/legend/_3_285.png" /> זמר<br />\
    <img src="styles/legend/_3_286.png" /> זמרת<br />\
    <img src="styles/legend/_3_287.png" /> זנוח<br />\
    <img src="styles/legend/_3_288.png" /> זרזיר<br />\
    <img src="styles/legend/_3_289.png" /> זרחיה<br />\
    <img src="styles/legend/_3_290.png" /> חבל אילות<br />\
    <img src="styles/legend/_3_291.png" /> חבל יבנה<br />\
    <img src="styles/legend/_3_292.png" /> חבל מודיעין<br />\
    <img src="styles/legend/_3_293.png" /> חברון<br />\
    <img src="styles/legend/_3_294.png" /> חגור<br />\
    <img src="styles/legend/_3_295.png" /> חגי<br />\
    <img src="styles/legend/_3_296.png" /> חד נס<br />\
    <img src="styles/legend/_3_297.png" /> חד-נס<br />\
    <img src="styles/legend/_3_298.png" /> חדיד<br />\
    <img src="styles/legend/_3_299.png" /> חדנס<br />\
    <img src="styles/legend/_3_300.png" /> חדרה<br />\
    <img src="styles/legend/_3_301.png" /> חולדה<br />\
    <img src="styles/legend/_3_302.png" /> חולון<br />\
    <img src="styles/legend/_3_303.png" /> חולית<br />\
    <img src="styles/legend/_3_304.png" /> חולתה<br />\
    <img src="styles/legend/_3_305.png" /> חוסן<br />\
    <img src="styles/legend/_3_306.png" /> חוף אשקלון<br />\
    <img src="styles/legend/_3_307.png" /> חוף השרון<br />\
    <img src="styles/legend/_3_308.png" /> חוקוק<br />\
    <img src="styles/legend/_3_309.png" /> חורה<br />\
    <img src="styles/legend/_3_310.png" /> חורפיש<br />\
    <img src="styles/legend/_3_311.png" /> חורשים<br />\
    <img src="styles/legend/_3_312.png" /> חילף<br />\
    <img src="styles/legend/_3_313.png" /> חיננית<br />\
    <img src="styles/legend/_3_314.png" /> חיפה<br />\
    <img src="styles/legend/_3_315.png" /> חירות<br />\
    <img src="styles/legend/_3_316.png" /> חלמיש<br />\
    <img src="styles/legend/_3_317.png" /> חלץ<br />\
    <img src="styles/legend/_3_318.png" /> חמד<br />\
    <img src="styles/legend/_3_319.png" /> חמדיה<br />\
    <img src="styles/legend/_3_320.png" /> חמדת<br />\
    <img src="styles/legend/_3_321.png" /> חמרה<br />\
    <img src="styles/legend/_3_322.png" /> חמת גדר<br />\
    <img src="styles/legend/_3_323.png" /> חניאל<br />\
    <img src="styles/legend/_3_324.png" /> חניתה<br />\
    <img src="styles/legend/_3_325.png" /> חפץ חיים<br />\
    <img src="styles/legend/_3_326.png" /> חפצי-בה<br />\
    <img src="styles/legend/_3_327.png" /> חפציבה<br />\
    <img src="styles/legend/_3_328.png" /> חצבה<br />\
    <img src="styles/legend/_3_329.png" /> חצור הגלילית<br />\
    <img src="styles/legend/_3_330.png" /> חצור-אשדוד<br />\
    <img src="styles/legend/_3_331.png" /> חצוראשדוד<br />\
    <img src="styles/legend/_3_332.png" /> חצרות יסף<br />\
    <img src="styles/legend/_3_333.png" /> חצרים<br />\
    <img src="styles/legend/_3_334.png" /> חרמון<br />\
    <img src="styles/legend/_3_335.png" /> חרמש<br />\
    <img src="styles/legend/_3_336.png" /> חרפיש<br />\
    <img src="styles/legend/_3_337.png" /> חשמונאים<br />\
    <img src="styles/legend/_3_338.png" /> טבריה<br />\
    <img src="styles/legend/_3_339.png" /> טובא זנגריה<br />\
    <img src="styles/legend/_3_340.png" /> טורעאן<br />\
    <img src="styles/legend/_3_341.png" /> טייבה<br />\
    <img src="styles/legend/_3_342.png" /> טייבה-במשולש<br />\
    <img src="styles/legend/_3_343.png" /> טייבהבמשולש<br />\
    <img src="styles/legend/_3_344.png" /> טירה<br />\
    <img src="styles/legend/_3_345.png" /> טירת הכרמל<br />\
    <img src="styles/legend/_3_346.png" /> טירת כרמל<br />\
    <img src="styles/legend/_3_347.png" /> טירת צבי<br />\
    <img src="styles/legend/_3_348.png" /> טל שחר<br />\
    <img src="styles/legend/_3_349.png" /> טללים<br />\
    <img src="styles/legend/_3_350.png" /> טלמון<br />\
    <img src="styles/legend/_3_351.png" /> טמרה<br />\
    <img src="styles/legend/_3_352.png" /> טנא<br />\
    <img src="styles/legend/_3_353.png" /> יאנוח-ג`ת<br />\
    <img src="styles/legend/_3_354.png" /> יאנוחג`ת<br />\
    <img src="styles/legend/_3_355.png" /> יבול<br />\
    <img src="styles/legend/_3_356.png" /> יבנאל<br />\
    <img src="styles/legend/_3_357.png" /> יבנה<br />\
    <img src="styles/legend/_3_358.png" /> יבניאל<br />\
    <img src="styles/legend/_3_359.png" /> יגור<br />\
    <img src="styles/legend/_3_360.png" /> יגל<br />\
    <img src="styles/legend/_3_361.png" /> יד בנימין<br />\
    <img src="styles/legend/_3_362.png" /> יד חנה<br />\
    <img src="styles/legend/_3_363.png" /> יד מרדכי<br />\
    <img src="styles/legend/_3_364.png" /> ידידיה<br />\
    <img src="styles/legend/_3_365.png" /> יהוד<br />\
    <img src="styles/legend/_3_366.png" /> יהוד-מונוסון<br />\
    <img src="styles/legend/_3_367.png" /> יהודיה<br />\
    <img src="styles/legend/_3_368.png" /> יהל<br />\
    <img src="styles/legend/_3_369.png" /> יואב<br />\
    <img src="styles/legend/_3_370.png" /> יובלים<br />\
    <img src="styles/legend/_3_371.png" /> יונתן<br />\
    <img src="styles/legend/_3_372.png" /> יוקנעם<br />\
    <img src="styles/legend/_3_373.png" /> יוקנעם עילית<br />\
    <img src="styles/legend/_3_374.png" /> יוקנעם-מושבה<br />\
    <img src="styles/legend/_3_375.png" /> יוקנעםמושבה<br />\
    <img src="styles/legend/_3_376.png" /> יושיביה<br />\
    <img src="styles/legend/_3_377.png" /> יזרעאל<br />\
    <img src="styles/legend/_3_378.png" /> יטבתה<br />\
    <img src="styles/legend/_3_379.png" /> ייט"ב<br />\
    <img src="styles/legend/_3_380.png" /> ייט``ב<br />\
    <img src="styles/legend/_3_381.png" /> יכיני<br />\
    <img src="styles/legend/_3_382.png" /> ים המלח<br />\
    <img src="styles/legend/_3_383.png" /> ינוב<br />\
    <img src="styles/legend/_3_384.png" /> ינון<br />\
    <img src="styles/legend/_3_385.png" /> יסוד המעלה<br />\
    <img src="styles/legend/_3_386.png" /> יסודות<br />\
    <img src="styles/legend/_3_387.png" /> יסעור<br />\
    <img src="styles/legend/_3_388.png" /> יעד<br />\
    <img src="styles/legend/_3_389.png" /> יערה<br />\
    <img src="styles/legend/_3_390.png" /> יפיע<br />\
    <img src="styles/legend/_3_391.png" /> יפית<br />\
    <img src="styles/legend/_3_392.png" /> יפעת<br />\
    <img src="styles/legend/_3_393.png" /> יפתח<br />\
    <img src="styles/legend/_3_394.png" /> יצהר<br />\
    <img src="styles/legend/_3_395.png" /> יציץ<br />\
    <img src="styles/legend/_3_396.png" /> יקום<br />\
    <img src="styles/legend/_3_397.png" /> יקנעם<br />\
    <img src="styles/legend/_3_398.png" /> יקנעם  מושבה<br />\
    <img src="styles/legend/_3_399.png" /> יקנעם עילית<br />\
    <img src="styles/legend/_3_400.png" /> יראון<br />\
    <img src="styles/legend/_3_401.png" /> ירדנה<br />\
    <img src="styles/legend/_3_402.png" /> ירוחם<br />\
    <img src="styles/legend/_3_403.png" /> ירושלים<br />\
    <img src="styles/legend/_3_404.png" /> ירחיב<br />\
    <img src="styles/legend/_3_405.png" /> יריחו<br />\
    <img src="styles/legend/_3_406.png" /> ירכא<br />\
    <img src="styles/legend/_3_407.png" /> ירקונה<br />\
    <img src="styles/legend/_3_408.png" /> ישע<br />\
    <img src="styles/legend/_3_409.png" /> ישעי<br />\
    <img src="styles/legend/_3_410.png" /> ישרש<br />\
    <img src="styles/legend/_3_411.png" /> כאבול<br />\
    <img src="styles/legend/_3_412.png" /> כסיפה<br />\
    <img src="styles/legend/_3_413.png" /> כסלון<br />\
    <img src="styles/legend/_3_414.png" /> כעביה טבאש<br />\
    <img src="styles/legend/_3_415.png" /> כפר אדומים<br />\
    <img src="styles/legend/_3_416.png" /> כפר אז``ר<br />\
    <img src="styles/legend/_3_417.png" /> כפר אזר<br />\
    <img src="styles/legend/_3_418.png" /> כפר ביאליק<br />\
    <img src="styles/legend/_3_419.png" /> כפר ביל"ו<br />\
    <img src="styles/legend/_3_420.png" /> כפר ביל``ו<br />\
    <img src="styles/legend/_3_421.png" /> כפר בילו<br />\
    <img src="styles/legend/_3_422.png" /> כפר בלום<br />\
    <img src="styles/legend/_3_423.png" /> כפר בן נון<br />\
    <img src="styles/legend/_3_424.png" /> כפר ברא<br />\
    <img src="styles/legend/_3_425.png" /> כפר ברוך<br />\
    <img src="styles/legend/_3_426.png" /> כפר גדעון<br />\
    <img src="styles/legend/_3_427.png" /> כפר גלים<br />\
    <img src="styles/legend/_3_428.png" /> כפר גליקסון<br />\
    <img src="styles/legend/_3_429.png" /> כפר גלעדי<br />\
    <img src="styles/legend/_3_430.png" /> כפר דניאל<br />\
    <img src="styles/legend/_3_431.png" /> כפר האורנים<br />\
    <img src="styles/legend/_3_432.png" /> כפר החורש<br />\
    <img src="styles/legend/_3_433.png" /> כפר המכבי<br />\
    <img src="styles/legend/_3_434.png" /> כפר הנגיד<br />\
    <img src="styles/legend/_3_435.png" /> כפר הנשיא<br />\
    <img src="styles/legend/_3_436.png" /> כפר הס<br />\
    <img src="styles/legend/_3_437.png" /> כפר הראה<br />\
    <img src="styles/legend/_3_438.png" /> כפר הריף<br />\
    <img src="styles/legend/_3_439.png" /> כפר ויתקין<br />\
    <img src="styles/legend/_3_440.png" /> כפר זיו<br />\
    <img src="styles/legend/_3_441.png" /> כפר חב"ד<br />\
    <img src="styles/legend/_3_442.png" /> כפר חב``ד<br />\
    <img src="styles/legend/_3_443.png" /> כפר חבד<br />\
    <img src="styles/legend/_3_444.png" /> כפר חושן<br />\
    <img src="styles/legend/_3_445.png" /> כפר חיטים<br />\
    <img src="styles/legend/_3_446.png" /> כפר חסידים א<br />\
    <img src="styles/legend/_3_447.png" /> כפר חרוב<br />\
    <img src="styles/legend/_3_448.png" /> כפר טרומן<br />\
    <img src="styles/legend/_3_449.png" /> כפר יהושע<br />\
    <img src="styles/legend/_3_450.png" /> כפר יונה<br />\
    <img src="styles/legend/_3_451.png" /> כפר יעבץ<br />\
    <img src="styles/legend/_3_452.png" /> כפר כמא<br />\
    <img src="styles/legend/_3_453.png" /> כפר כנא<br />\
    <img src="styles/legend/_3_454.png" /> כפר מונש<br />\
    <img src="styles/legend/_3_455.png" /> כפר מנדא<br />\
    <img src="styles/legend/_3_456.png" /> כפר מנחם<br />\
    <img src="styles/legend/_3_457.png" /> כפר מסריק<br />\
    <img src="styles/legend/_3_458.png" /> כפר נטר<br />\
    <img src="styles/legend/_3_459.png" /> כפר סאלד<br />\
    <img src="styles/legend/_3_460.png" /> כפר סבא<br />\
    <img src="styles/legend/_3_461.png" /> כפר סילבר<br />\
    <img src="styles/legend/_3_462.png" /> כפר סירקין<br />\
    <img src="styles/legend/_3_463.png" /> כפר עזה<br />\
    <img src="styles/legend/_3_464.png" /> כפר עזון<br />\
    <img src="styles/legend/_3_465.png" /> כפר עציון<br />\
    <img src="styles/legend/_3_466.png" /> כפר פינס<br />\
    <img src="styles/legend/_3_467.png" /> כפר קאסם<br />\
    <img src="styles/legend/_3_468.png" /> כפר קרע<br />\
    <img src="styles/legend/_3_469.png" /> כפר ראש הנקרה<br />\
    <img src="styles/legend/_3_470.png" /> כפר רוזנואלד (זרעית)<br />\
    <img src="styles/legend/_3_471.png" /> כפר רופין<br />\
    <img src="styles/legend/_3_472.png" /> כפר רות<br />\
    <img src="styles/legend/_3_473.png" /> כפר שמאי<br />\
    <img src="styles/legend/_3_474.png" /> כפר שמואל<br />\
    <img src="styles/legend/_3_475.png" /> כפר שמריהו<br />\
    <img src="styles/legend/_3_476.png" /> כפר תבור<br />\
    <img src="styles/legend/_3_477.png" /> כפר תפוח<br />\
    <img src="styles/legend/_3_478.png" /> כרכום<br />\
    <img src="styles/legend/_3_479.png" /> כרם מהר``ל<br />\
    <img src="styles/legend/_3_480.png" /> כרם מהרל<br />\
    <img src="styles/legend/_3_481.png" /> כרם שלום<br />\
    <img src="styles/legend/_3_482.png" /> כרמי יוסף<br />\
    <img src="styles/legend/_3_483.png" /> כרמי צור<br />\
    <img src="styles/legend/_3_484.png" /> כרמיאל<br />\
    <img src="styles/legend/_3_485.png" /> כרמיה<br />\
    <img src="styles/legend/_3_486.png" /> כרמים<br />\
    <img src="styles/legend/_3_487.png" /> כרמל<br />\
    <img src="styles/legend/_3_488.png" /> לב השרון<br />\
    <img src="styles/legend/_3_489.png" /> לבון<br />\
    <img src="styles/legend/_3_490.png" /> לביא<br />\
    <img src="styles/legend/_3_491.png" /> להב<br />\
    <img src="styles/legend/_3_492.png" /> להבות חביבה<br />\
    <img src="styles/legend/_3_493.png" /> להבים<br />\
    <img src="styles/legend/_3_494.png" /> לוד<br />\
    <img src="styles/legend/_3_495.png" /> לוחמי הגיטאות<br />\
    <img src="styles/legend/_3_496.png" /> לוטם<br />\
    <img src="styles/legend/_3_497.png" /> לוטן<br />\
    <img src="styles/legend/_3_498.png" /> לימן<br />\
    <img src="styles/legend/_3_499.png" /> לכיש<br />\
    <img src="styles/legend/_3_500.png" /> לפיד<br />\
    <img src="styles/legend/_3_501.png" /> לפידות<br />\
    <img src="styles/legend/_3_502.png" /> לקיה<br />\
    <img src="styles/legend/_3_503.png" /> מ.א מטה יהודה<br />\
    <img src="styles/legend/_3_504.png" /> מאור<br />\
    <img src="styles/legend/_3_505.png" /> מבוא ביתר<br />\
    <img src="styles/legend/_3_506.png" /> מבוא דותן<br />\
    <img src="styles/legend/_3_507.png" /> מבוא העמקים<br />\
    <img src="styles/legend/_3_508.png" /> מבוא חורון<br />\
    <img src="styles/legend/_3_509.png" /> מבוא חמה<br />\
    <img src="styles/legend/_3_510.png" /> מבוא מודיעים<br />\
    <img src="styles/legend/_3_511.png" /> מבואות החרמון<br />\
    <img src="styles/legend/_3_512.png" /> מבועים<br />\
    <img src="styles/legend/_3_513.png" /> מבטחים<br />\
    <img src="styles/legend/_3_514.png" /> מבקיעים<br />\
    <img src="styles/legend/_3_515.png" /> מבשרת ציון<br />\
    <img src="styles/legend/_3_516.png" /> מג`ד אל כרום<br />\
    <img src="styles/legend/_3_517.png" /> מג`ד אל-כרום<br />\
    <img src="styles/legend/_3_518.png" /> מג`ד אלכרום<br />\
    <img src="styles/legend/_3_519.png" /> מג`דל שמס<br />\
    <img src="styles/legend/_3_520.png" /> מגאר<br />\
    <img src="styles/legend/_3_521.png" /> מגד אל כרום<br />\
    <img src="styles/legend/_3_522.png" /> מגדל<br />\
    <img src="styles/legend/_3_523.png" /> מגדל העמק<br />\
    <img src="styles/legend/_3_524.png" /> מגדל שמס<br />\
    <img src="styles/legend/_3_525.png" /> מגדל תפן<br />\
    <img src="styles/legend/_3_526.png" /> מגדלים<br />\
    <img src="styles/legend/_3_527.png" /> מגידו<br />\
    <img src="styles/legend/_3_528.png" /> מגילות<br />\
    <img src="styles/legend/_3_529.png" /> מגל<br />\
    <img src="styles/legend/_3_530.png" /> מגן<br />\
    <img src="styles/legend/_3_531.png" /> מגן שאול<br />\
    <img src="styles/legend/_3_532.png" /> מגשימים<br />\
    <img src="styles/legend/_3_533.png" /> מדרך עוז<br />\
    <img src="styles/legend/_3_534.png" /> מדרשת בן גוריון<br />\
    <img src="styles/legend/_3_535.png" /> מודיעין<br />\
    <img src="styles/legend/_3_536.png" /> מודיעין מכבים רעות<br />\
    <img src="styles/legend/_3_537.png" /> מודיעין עילית<br />\
    <img src="styles/legend/_3_538.png" /> מודיעין-מכבים-רעות<br />\
    <img src="styles/legend/_3_539.png" /> מולדת<br />\
    <img src="styles/legend/_3_540.png" /> מועאוויה<br />\
    <img src="styles/legend/_3_541.png" /> מורן<br />\
    <img src="styles/legend/_3_542.png" /> מורשת<br />\
    <img src="styles/legend/_3_543.png" /> מזור<br />\
    <img src="styles/legend/_3_544.png" /> מזכרת בתיה<br />\
    <img src="styles/legend/_3_545.png" /> מזרע<br />\
    <img src="styles/legend/_3_546.png" /> מחוזית חיפה<br />\
    <img src="styles/legend/_3_547.png" /> מחולה<br />\
    <img src="styles/legend/_3_548.png" /> מחים פרעה<br />\
    <img src="styles/legend/_3_549.png" /> מחניים<br />\
    <img src="styles/legend/_3_550.png" /> מחסיה<br />\
    <img src="styles/legend/_3_551.png" /> מטה אשר<br />\
    <img src="styles/legend/_3_552.png" /> מטה בנימין<br />\
    <img src="styles/legend/_3_553.png" /> מטה יהודה<br />\
    <img src="styles/legend/_3_554.png" /> מטולה<br />\
    <img src="styles/legend/_3_555.png" /> מטע<br />\
    <img src="styles/legend/_3_556.png" /> מי עמי<br />\
    <img src="styles/legend/_3_557.png" /> מיסר<br />\
    <img src="styles/legend/_3_558.png" /> מירון<br />\
    <img src="styles/legend/_3_559.png" /> מישור אדומים<br />\
    <img src="styles/legend/_3_560.png" /> מישור מנוחה<br />\
    <img src="styles/legend/_3_561.png" /> מיתר<br />\
    <img src="styles/legend/_3_562.png" /> מכבים-רעות<br />\
    <img src="styles/legend/_3_563.png" /> מכביםרעות<br />\
    <img src="styles/legend/_3_564.png" /> מכון וינגייט<br />\
    <img src="styles/legend/_3_565.png" /> מכורה<br />\
    <img src="styles/legend/_3_566.png" /> מכמורת<br />\
    <img src="styles/legend/_3_567.png" /> מלילות<br />\
    <img src="styles/legend/_3_568.png" /> מלכיה<br />\
    <img src="styles/legend/_3_569.png" /> מלכישוע<br />\
    <img src="styles/legend/_3_570.png" /> מנרה<br />\
    <img src="styles/legend/_3_571.png" /> מנשה<br />\
    <img src="styles/legend/_3_572.png" /> מסד<br />\
    <img src="styles/legend/_3_573.png" /> מסילות<br />\
    <img src="styles/legend/_3_574.png" /> מסילת ציון<br />\
    <img src="styles/legend/_3_575.png" /> מסעדה<br />\
    <img src="styles/legend/_3_576.png" /> מע`אר<br />\
    <img src="styles/legend/_3_577.png" /> מעאויה<br />\
    <img src="styles/legend/_3_578.png" /> מעאר<br />\
    <img src="styles/legend/_3_579.png" /> מעגן<br />\
    <img src="styles/legend/_3_580.png" /> מעגן מיכאל<br />\
    <img src="styles/legend/_3_581.png" /> מעוז חיים<br />\
    <img src="styles/legend/_3_582.png" /> מעון<br />\
    <img src="styles/legend/_3_583.png" /> מעיין צבי<br />\
    <img src="styles/legend/_3_584.png" /> מעיליא<br />\
    <img src="styles/legend/_3_585.png" /> מעין ברוך<br />\
    <img src="styles/legend/_3_586.png" /> מעין צבי<br />\
    <img src="styles/legend/_3_587.png" /> מעלה אדומים<br />\
    <img src="styles/legend/_3_588.png" /> מעלה אפרים<br />\
    <img src="styles/legend/_3_589.png" /> מעלה גלבוע<br />\
    <img src="styles/legend/_3_590.png" /> מעלה גמלא<br />\
    <img src="styles/legend/_3_591.png" /> מעלה החמישה<br />\
    <img src="styles/legend/_3_592.png" /> מעלה חרמון<br />\
    <img src="styles/legend/_3_593.png" /> מעלה יוסף<br />\
    <img src="styles/legend/_3_594.png" /> מעלה לבונה<br />\
    <img src="styles/legend/_3_595.png" /> מעלה מכמ``ש<br />\
    <img src="styles/legend/_3_596.png" /> מעלה מכמש<br />\
    <img src="styles/legend/_3_597.png" /> מעלה עירון<br />\
    <img src="styles/legend/_3_598.png" /> מעלה שומרון<br />\
    <img src="styles/legend/_3_599.png" /> מעלות תרשיחא<br />\
    <img src="styles/legend/_3_600.png" /> מעלות-תרשיחא<br />\
    <img src="styles/legend/_3_601.png" /> מענית<br />\
    <img src="styles/legend/_3_602.png" /> מעש<br />\
    <img src="styles/legend/_3_603.png" /> מפלסים<br />\
    <img src="styles/legend/_3_604.png" /> מצדה<br />\
    <img src="styles/legend/_3_605.png" /> מצדות יהודה<br />\
    <img src="styles/legend/_3_606.png" /> מצובה<br />\
    <img src="styles/legend/_3_607.png" /> מצודת יהודה<br />\
    <img src="styles/legend/_3_608.png" /> מצליח<br />\
    <img src="styles/legend/_3_609.png" /> מצפה אבי"ב<br />\
    <img src="styles/legend/_3_610.png" /> מצפה אבי``ב<br />\
    <img src="styles/legend/_3_611.png" /> מצפה חגית<br />\
    <img src="styles/legend/_3_612.png" /> מצפה יריחו<br />\
    <img src="styles/legend/_3_613.png" /> מצפה נטופה<br />\
    <img src="styles/legend/_3_614.png" /> מצפה רמון<br />\
    <img src="styles/legend/_3_615.png" /> מצפה שלם<br />\
    <img src="styles/legend/_3_616.png" /> מצר<br />\
    <img src="styles/legend/_3_617.png" /> מקווה ישראל<br />\
    <img src="styles/legend/_3_618.png" /> מרגליות<br />\
    <img src="styles/legend/_3_619.png" /> מרום גולן<br />\
    <img src="styles/legend/_3_620.png" /> מרום הגליל<br />\
    <img src="styles/legend/_3_621.png" /> מרחביה-קיבוץ<br />\
    <img src="styles/legend/_3_622.png" /> מרחביהקיבוץ<br />\
    <img src="styles/legend/_3_623.png" /> מרחבים<br />\
    <img src="styles/legend/_3_624.png" /> משאבי שדה<br />\
    <img src="styles/legend/_3_625.png" /> משגב<br />\
    <img src="styles/legend/_3_626.png" /> משגב דב<br />\
    <img src="styles/legend/_3_627.png" /> משגב עם<br />\
    <img src="styles/legend/_3_628.png" /> משהד<br />\
    <img src="styles/legend/_3_629.png" /> משואות יצחק<br />\
    <img src="styles/legend/_3_630.png" /> משכיות<br />\
    <img src="styles/legend/_3_631.png" /> משמר איילון<br />\
    <img src="styles/legend/_3_632.png" /> משמר אילון<br />\
    <img src="styles/legend/_3_633.png" /> משמר דוד<br />\
    <img src="styles/legend/_3_634.png" /> משמר הנגב<br />\
    <img src="styles/legend/_3_635.png" /> משמר העמק<br />\
    <img src="styles/legend/_3_636.png" /> משמר השבעה<br />\
    <img src="styles/legend/_3_637.png" /> משמר השרון<br />\
    <img src="styles/legend/_3_638.png" /> משמרות<br />\
    <img src="styles/legend/_3_639.png" /> משמרת<br />\
    <img src="styles/legend/_3_640.png" /> מתן<br />\
    <img src="styles/legend/_3_641.png" /> מתת<br />\
    <img src="styles/legend/_3_642.png" /> מתתיהו<br />\
    <img src="styles/legend/_3_643.png" /> נאות גולן<br />\
    <img src="styles/legend/_3_644.png" /> נאות הכיכר<br />\
    <img src="styles/legend/_3_645.png" /> נאות הככר<br />\
    <img src="styles/legend/_3_646.png" /> נאות מרדכי<br />\
    <img src="styles/legend/_3_647.png" /> נאות סמדר<br />\
    <img src="styles/legend/_3_648.png" /> נאעורה<br />\
    <img src="styles/legend/_3_649.png" /> נבטים<br />\
    <img src="styles/legend/_3_650.png" /> נגבה<br />\
    <img src="styles/legend/_3_651.png" /> נגוהות<br />\
    <img src="styles/legend/_3_652.png" /> נהלל<br />\
    <img src="styles/legend/_3_653.png" /> נהריה<br />\
    <img src="styles/legend/_3_654.png" /> נוב<br />\
    <img src="styles/legend/_3_655.png" /> נוה אטיב<br />\
    <img src="styles/legend/_3_656.png" /> נוה אילן<br />\
    <img src="styles/legend/_3_657.png" /> נוה דניאל<br />\
    <img src="styles/legend/_3_658.png" /> נוה זוהר<br />\
    <img src="styles/legend/_3_659.png" /> נוה ימין<br />\
    <img src="styles/legend/_3_660.png" /> נוה ירק<br />\
    <img src="styles/legend/_3_661.png" /> נוה מיכאל<br />\
    <img src="styles/legend/_3_662.png" /> נווה אור<br />\
    <img src="styles/legend/_3_663.png" /> נווה אטי``ב<br />\
    <img src="styles/legend/_3_664.png" /> נווה אילן<br />\
    <img src="styles/legend/_3_665.png" /> נווה דניאל<br />\
    <img src="styles/legend/_3_666.png" /> נווה זוהר<br />\
    <img src="styles/legend/_3_667.png" /> נווה זיו<br />\
    <img src="styles/legend/_3_668.png" /> נווה חריף<br />\
    <img src="styles/legend/_3_669.png" /> נווה ים<br />\
    <img src="styles/legend/_3_670.png" /> נווה ימין<br />\
    <img src="styles/legend/_3_671.png" /> נווה ירק<br />\
    <img src="styles/legend/_3_672.png" /> נווה מונוסון<br />\
    <img src="styles/legend/_3_673.png" /> נווה מונסון<br />\
    <img src="styles/legend/_3_674.png" /> נווה שלום<br />\
    <img src="styles/legend/_3_675.png" /> נועם<br />\
    <img src="styles/legend/_3_676.png" /> נוף הגליל<br />\
    <img src="styles/legend/_3_677.png" /> נופי סלע<br />\
    <img src="styles/legend/_3_678.png" /> נופים<br />\
    <img src="styles/legend/_3_679.png" /> נופית<br />\
    <img src="styles/legend/_3_680.png" /> נוקדים<br />\
    <img src="styles/legend/_3_681.png" /> נורדיה<br />\
    <img src="styles/legend/_3_682.png" /> נח``ל עוז<br />\
    <img src="styles/legend/_3_683.png" /> נחושה<br />\
    <img src="styles/legend/_3_684.png" /> נחל עוז<br />\
    <img src="styles/legend/_3_685.png" /> נחלה<br />\
    <img src="styles/legend/_3_686.png" /> נחלים<br />\
    <img src="styles/legend/_3_687.png" /> נחם<br />\
    <img src="styles/legend/_3_688.png" /> נחף<br />\
    <img src="styles/legend/_3_689.png" /> נחשולים<br />\
    <img src="styles/legend/_3_690.png" /> נחשון<br />\
    <img src="styles/legend/_3_691.png" /> נחשונים<br />\
    <img src="styles/legend/_3_692.png" /> נטועה<br />\
    <img src="styles/legend/_3_693.png" /> נטור<br />\
    <img src="styles/legend/_3_694.png" /> נטף<br />\
    <img src="styles/legend/_3_695.png" /> ניל"י<br />\
    <img src="styles/legend/_3_696.png" /> ניל``י<br />\
    <img src="styles/legend/_3_697.png" /> נין<br />\
    <img src="styles/legend/_3_698.png" /> ניצן<br />\
    <img src="styles/legend/_3_699.png" /> ניצנה<br />\
    <img src="styles/legend/_3_700.png" /> ניצנה  קהילת חינוך<br />\
    <img src="styles/legend/_3_701.png" /> ניצני סיני<br />\
    <img src="styles/legend/_3_702.png" /> ניצני עוז<br />\
    <img src="styles/legend/_3_703.png" /> ניצנים<br />\
    <img src="styles/legend/_3_704.png" /> ניר אליהו<br />\
    <img src="styles/legend/_3_705.png" /> ניר בנים<br />\
    <img src="styles/legend/_3_706.png" /> ניר דוד<br />\
    <img src="styles/legend/_3_707.png" /> ניר דוד (תל עמל)<br />\
    <img src="styles/legend/_3_708.png" /> ניר ח``ן<br />\
    <img src="styles/legend/_3_709.png" /> ניר יפה<br />\
    <img src="styles/legend/_3_710.png" /> ניר יצחק<br />\
    <img src="styles/legend/_3_711.png" /> ניר עוז<br />\
    <img src="styles/legend/_3_712.png" /> ניר עם<br />\
    <img src="styles/legend/_3_713.png" /> ניר עציון<br />\
    <img src="styles/legend/_3_714.png" /> ניר עקיבא<br />\
    <img src="styles/legend/_3_715.png" /> ניר צבי<br />\
    <img src="styles/legend/_3_716.png" /> נירים<br />\
    <img src="styles/legend/_3_717.png" /> נירית<br />\
    <img src="styles/legend/_3_718.png" /> נס הרים<br />\
    <img src="styles/legend/_3_719.png" /> נס ציונה<br />\
    <img src="styles/legend/_3_720.png" /> נעמ"ה<br />\
    <img src="styles/legend/_3_721.png" /> נעמה<br />\
    <img src="styles/legend/_3_722.png" /> נען<br />\
    <img src="styles/legend/_3_723.png" /> נצר סירני<br />\
    <img src="styles/legend/_3_724.png" /> נצר סרני<br />\
    <img src="styles/legend/_3_725.png" /> נצרת<br />\
    <img src="styles/legend/_3_726.png" /> נצרת עילית<br />\
    <img src="styles/legend/_3_727.png" /> נשר<br />\
    <img src="styles/legend/_3_728.png" /> נתיב הגדוד<br />\
    <img src="styles/legend/_3_729.png" /> נתיב הל"ה<br />\
    <img src="styles/legend/_3_730.png" /> נתיב העשרה<br />\
    <img src="styles/legend/_3_731.png" /> נתיב השיירה<br />\
    <img src="styles/legend/_3_732.png" /> נתיבות<br />\
    <img src="styles/legend/_3_733.png" /> נתניה<br />\
    <img src="styles/legend/_3_734.png" /> סאסא<br />\
    <img src="styles/legend/_3_735.png" /> סביון<br />\
    <img src="styles/legend/_3_736.png" /> סג`ור<br />\
    <img src="styles/legend/_3_737.png" /> סוסיה<br />\
    <img src="styles/legend/_3_738.png" /> סופה<br />\
    <img src="styles/legend/_3_739.png" /> סח`נין<br />\
    <img src="styles/legend/_3_740.png" /> סחנין<br />\
    <img src="styles/legend/_3_741.png" /> סכנין<br />\
    <img src="styles/legend/_3_742.png" /> סלעית<br />\
    <img src="styles/legend/_3_743.png" /> סמר<br />\
    <img src="styles/legend/_3_744.png" /> סעד<br />\
    <img src="styles/legend/_3_745.png" /> סער<br />\
    <img src="styles/legend/_3_746.png" /> ספיר<br />\
    <img src="styles/legend/_3_747.png" /> ספסופה<br />\
    <img src="styles/legend/_3_748.png" /> עברון<br />\
    <img src="styles/legend/_3_749.png" /> עגור<br />\
    <img src="styles/legend/_3_750.png" /> עד הלום<br />\
    <img src="styles/legend/_3_751.png" /> עדי<br />\
    <img src="styles/legend/_3_752.png" /> עוזה<br />\
    <img src="styles/legend/_3_753.png" /> עולש<br />\
    <img src="styles/legend/_3_754.png" /> עומר<br />\
    <img src="styles/legend/_3_755.png" /> עוספיה<br />\
    <img src="styles/legend/_3_756.png" /> עופר<br />\
    <img src="styles/legend/_3_757.png" /> עופרה<br />\
    <img src="styles/legend/_3_758.png" /> עופרים<br />\
    <img src="styles/legend/_3_759.png" /> עוצם<br />\
    <img src="styles/legend/_3_760.png" /> עותניאל<br />\
    <img src="styles/legend/_3_761.png" /> עזריאל<br />\
    <img src="styles/legend/_3_762.png" /> עזריה<br />\
    <img src="styles/legend/_3_763.png" /> עזריקם<br />\
    <img src="styles/legend/_3_764.png" /> עזתה<br />\
    <img src="styles/legend/_3_765.png" /> עטרת<br />\
    <img src="styles/legend/_3_766.png" /> עיילבון<br />\
    <img src="styles/legend/_3_767.png" /> עילבון<br />\
    <img src="styles/legend/_3_768.png" /> עילוט<br />\
    <img src="styles/legend/_3_769.png" /> עין בוקק<br />\
    <img src="styles/legend/_3_770.png" /> עין גב<br />\
    <img src="styles/legend/_3_771.png" /> עין גדי<br />\
    <img src="styles/legend/_3_772.png" /> עין דור<br />\
    <img src="styles/legend/_3_773.png" /> עין הבשור<br />\
    <img src="styles/legend/_3_774.png" /> עין החורש<br />\
    <img src="styles/legend/_3_775.png" /> עין המפרץ<br />\
    <img src="styles/legend/_3_776.png" /> עין הנצי``ב<br />\
    <img src="styles/legend/_3_777.png" /> עין הנציב<br />\
    <img src="styles/legend/_3_778.png" /> עין העמק<br />\
    <img src="styles/legend/_3_779.png" /> עין השופט<br />\
    <img src="styles/legend/_3_780.png" /> עין ורד<br />\
    <img src="styles/legend/_3_781.png" /> עין זיוון<br />\
    <img src="styles/legend/_3_782.png" /> עין חצבה<br />\
    <img src="styles/legend/_3_783.png" /> עין חרוד איחוד<br />\
    <img src="styles/legend/_3_784.png" /> עין יהב<br />\
    <img src="styles/legend/_3_785.png" /> עין יעקב<br />\
    <img src="styles/legend/_3_786.png" /> עין כרמל<br />\
    <img src="styles/legend/_3_787.png" /> עין צורים<br />\
    <img src="styles/legend/_3_788.png" /> עין קנייא<br />\
    <img src="styles/legend/_3_789.png" /> עין שמר<br />\
    <img src="styles/legend/_3_790.png" /> עין תמר<br />\
    <img src="styles/legend/_3_791.png" /> עינב<br />\
    <img src="styles/legend/_3_792.png" /> עינת<br />\
    <img src="styles/legend/_3_793.png" /> עיר אובות<br />\
    <img src="styles/legend/_3_794.png" /> עירון<br />\
    <img src="styles/legend/_3_795.png" /> עכו<br />\
    <img src="styles/legend/_3_796.png" /> עלומים<br />\
    <img src="styles/legend/_3_797.png" /> עלי<br />\
    <img src="styles/legend/_3_798.png" /> עלי זהב<br />\
    <img src="styles/legend/_3_799.png" /> עלמה<br />\
    <img src="styles/legend/_3_800.png" /> עמינדב<br />\
    <img src="styles/legend/_3_801.png" /> עמיעד<br />\
    <img src="styles/legend/_3_802.png" /> עמיעוז<br />\
    <img src="styles/legend/_3_803.png" /> עמיקם<br />\
    <img src="styles/legend/_3_804.png" /> עמיר<br />\
    <img src="styles/legend/_3_805.png" /> עמנואל<br />\
    <img src="styles/legend/_3_806.png" /> עמק הירדן<br />\
    <img src="styles/legend/_3_807.png" /> עמק המעיינות<br />\
    <img src="styles/legend/_3_808.png" /> עמק חפר<br />\
    <img src="styles/legend/_3_809.png" /> עמק לוד<br />\
    <img src="styles/legend/_3_810.png" /> עמקה<br />\
    <img src="styles/legend/_3_811.png" /> ענב<br />\
    <img src="styles/legend/_3_812.png" /> עספיא<br />\
    <img src="styles/legend/_3_813.png" /> עפולה<br />\
    <img src="styles/legend/_3_814.png" /> עץ אפרים<br />\
    <img src="styles/legend/_3_815.png" /> ערבה<br />\
    <img src="styles/legend/_3_816.png" /> ערבות הירדן<br />\
    <img src="styles/legend/_3_817.png" /> ערד<br />\
    <img src="styles/legend/_3_818.png" /> ערוער<br />\
    <img src="styles/legend/_3_819.png" /> ערערה<br />\
    <img src="styles/legend/_3_820.png" /> ערערה-בנגב<br />\
    <img src="styles/legend/_3_821.png" /> עשרת<br />\
    <img src="styles/legend/_3_822.png" /> עתלית<br />\
    <img src="styles/legend/_3_823.png" /> עתניאל<br />\
    <img src="styles/legend/_3_824.png" /> פארן<br />\
    <img src="styles/legend/_3_825.png" /> פדואל<br />\
    <img src="styles/legend/_3_826.png" /> פדיה<br />\
    <img src="styles/legend/_3_827.png" /> פוריה - נווה עובד<br />\
    <img src="styles/legend/_3_828.png" /> פוריה עילית<br />\
    <img src="styles/legend/_3_829.png" /> פוריידיס<br />\
    <img src="styles/legend/_3_830.png" /> פורת<br />\
    <img src="styles/legend/_3_831.png" /> פטיש<br />\
    <img src="styles/legend/_3_832.png" /> פלך<br />\
    <img src="styles/legend/_3_833.png" /> פלמחים<br />\
    <img src="styles/legend/_3_834.png" /> פני חבר<br />\
    <img src="styles/legend/_3_835.png" /> פסגות<br />\
    <img src="styles/legend/_3_836.png" /> פסוטה<br />\
    <img src="styles/legend/_3_837.png" /> פצאל<br />\
    <img src="styles/legend/_3_838.png" /> פקיעין<br />\
    <img src="styles/legend/_3_839.png" /> פקיעין חדשה<br />\
    <img src="styles/legend/_3_840.png" /> פרדס חנה כרכור<br />\
    <img src="styles/legend/_3_841.png" /> פרדס חנה-כרכור<br />\
    <img src="styles/legend/_3_842.png" /> פרדס חנהכרכור<br />\
    <img src="styles/legend/_3_843.png" /> פרדסייה<br />\
    <img src="styles/legend/_3_844.png" /> פרוד<br />\
    <img src="styles/legend/_3_845.png" /> פתח תקווה<br />\
    <img src="styles/legend/_3_846.png" /> פתח-תקווה<br />\
    <img src="styles/legend/_3_847.png" /> פתחיה<br />\
    <img src="styles/legend/_3_848.png" /> פתחתקווה<br />\
    <img src="styles/legend/_3_849.png" /> צאלים<br />\
    <img src="styles/legend/_3_850.png" /> צובה<br />\
    <img src="styles/legend/_3_851.png" /> צופים<br />\
    <img src="styles/legend/_3_852.png" /> צופר<br />\
    <img src="styles/legend/_3_853.png" /> צוקים<br />\
    <img src="styles/legend/_3_854.png" /> צור הדסה<br />\
    <img src="styles/legend/_3_855.png" /> צור יצחק<br />\
    <img src="styles/legend/_3_856.png" /> צור משה<br />\
    <img src="styles/legend/_3_857.png" /> צור נתן<br />\
    <img src="styles/legend/_3_858.png" /> צוריאל<br />\
    <img src="styles/legend/_3_859.png" /> צורן<br />\
    <img src="styles/legend/_3_860.png" /> ציפורי<br />\
    <img src="styles/legend/_3_861.png" /> צפריה<br />\
    <img src="styles/legend/_3_862.png" /> צפת<br />\
    <img src="styles/legend/_3_863.png" /> צרעה<br />\
    <img src="styles/legend/_3_864.png" /> קבוץ מרחביה<br />\
    <img src="styles/legend/_3_865.png" /> קבוצת יבנה<br />\
    <img src="styles/legend/_3_866.png" /> קבוצת שילר<br />\
    <img src="styles/legend/_3_867.png" /> קדומים<br />\
    <img src="styles/legend/_3_868.png" /> קדימה<br />\
    <img src="styles/legend/_3_869.png" /> קדימה-צורן<br />\
    <img src="styles/legend/_3_870.png" /> קדמת צבי<br />\
    <img src="styles/legend/_3_871.png" /> קדרים<br />\
    <img src="styles/legend/_3_872.png" /> קוממיות<br />\
    <img src="styles/legend/_3_873.png" /> קטורה<br />\
    <img src="styles/legend/_3_874.png" /> קיבוץ אילות<br />\
    <img src="styles/legend/_3_875.png" /> קיבוץ שמיר<br />\
    <img src="styles/legend/_3_876.png" /> קיסריה<br />\
    <img src="styles/legend/_3_877.png" /> קליה<br />\
    <img src="styles/legend/_3_878.png" /> קלמניה<br />\
    <img src="styles/legend/_3_879.png" /> קלנסואה<br />\
    <img src="styles/legend/_3_880.png" /> קלנסווה<br />\
    <img src="styles/legend/_3_881.png" /> קלע<br />\
    <img src="styles/legend/_3_882.png" /> קמ``ג<br />\
    <img src="styles/legend/_3_883.png" /> קציר<br />\
    <img src="styles/legend/_3_884.png" /> קציר חריש<br />\
    <img src="styles/legend/_3_885.png" /> קצרין<br />\
    <img src="styles/legend/_3_886.png" /> קריות<br />\
    <img src="styles/legend/_3_887.png" /> קריית אונו<br />\
    <img src="styles/legend/_3_888.png" /> קריית אתא<br />\
    <img src="styles/legend/_3_889.png" /> קריית ביאליק<br />\
    <img src="styles/legend/_3_890.png" /> קריית גת<br />\
    <img src="styles/legend/_3_891.png" /> קריית ים<br />\
    <img src="styles/legend/_3_892.png" /> קריית שמונה<br />\
    <img src="styles/legend/_3_893.png" /> קרית אונו<br />\
    <img src="styles/legend/_3_894.png" /> קרית ארבע<br />\
    <img src="styles/legend/_3_895.png" /> קרית אתא<br />\
    <img src="styles/legend/_3_896.png" /> קרית ביאליק<br />\
    <img src="styles/legend/_3_897.png" /> קרית גת<br />\
    <img src="styles/legend/_3_898.png" /> קרית חיים<br />\
    <img src="styles/legend/_3_899.png" /> קרית חרושת<br />\
    <img src="styles/legend/_3_900.png" /> קרית טבעון<br />\
    <img src="styles/legend/_3_901.png" /> קרית ים<br />\
    <img src="styles/legend/_3_902.png" /> קרית יערים<br />\
    <img src="styles/legend/_3_903.png" /> קרית מוצקין<br />\
    <img src="styles/legend/_3_904.png" /> קרית מלאכי<br />\
    <img src="styles/legend/_3_905.png" /> קרית ספר<br />\
    <img src="styles/legend/_3_906.png" /> קרית ענבים<br />\
    <img src="styles/legend/_3_907.png" /> קרית עקרון<br />\
    <img src="styles/legend/_3_908.png" /> קרית שמונה<br />\
    <img src="styles/legend/_3_909.png" /> קרני שומרון<br />\
    <img src="styles/legend/_3_910.png" /> קשת<br />\
    <img src="styles/legend/_3_911.png" /> קשת יהונתן<br />\
    <img src="styles/legend/_3_912.png" /> ראמה<br />\
    <img src="styles/legend/_3_913.png" /> ראש העין<br />\
    <img src="styles/legend/_3_914.png" /> ראש פינה<br />\
    <img src="styles/legend/_3_915.png" /> ראש צורים<br />\
    <img src="styles/legend/_3_916.png" /> ראשון לציון<br />\
    <img src="styles/legend/_3_917.png" /> רבדים<br />\
    <img src="styles/legend/_3_918.png" /> רביבים<br />\
    <img src="styles/legend/_3_919.png" /> רביד<br />\
    <img src="styles/legend/_3_920.png" /> רג`ר<br />\
    <img src="styles/legend/_3_921.png" /> רגבה<br />\
    <img src="styles/legend/_3_922.png" /> רגבים<br />\
    <img src="styles/legend/_3_923.png" /> רגר<br />\
    <img src="styles/legend/_3_924.png" /> רהט<br />\
    <img src="styles/legend/_3_925.png" /> רוחמה<br />\
    <img src="styles/legend/_3_926.png" /> רומת היב<br />\
    <img src="styles/legend/_3_927.png" /> רועי<br />\
    <img src="styles/legend/_3_928.png" /> רופין<br />\
    <img src="styles/legend/_3_929.png" /> רותם<br />\
    <img src="styles/legend/_3_930.png" /> רחובות<br />\
    <img src="styles/legend/_3_931.png" /> ריינה<br />\
    <img src="styles/legend/_3_932.png" /> רימונים<br />\
    <img src="styles/legend/_3_933.png" /> רכסים<br />\
    <img src="styles/legend/_3_934.png" /> רם און<br />\
    <img src="styles/legend/_3_935.png" /> רם-און<br />\
    <img src="styles/legend/_3_936.png" /> רםאון<br />\
    <img src="styles/legend/_3_937.png" /> רמות<br />\
    <img src="styles/legend/_3_938.png" /> רמות השבים<br />\
    <img src="styles/legend/_3_939.png" /> רמות מנשה<br />\
    <img src="styles/legend/_3_940.png" /> רמות נפתלי<br />\
    <img src="styles/legend/_3_941.png" /> רמלה<br />\
    <img src="styles/legend/_3_942.png" /> רמת אפעל<br />\
    <img src="styles/legend/_3_943.png" /> רמת בת שמש<br />\
    <img src="styles/legend/_3_944.png" /> רמת גן<br />\
    <img src="styles/legend/_3_945.png" /> רמת דוד<br />\
    <img src="styles/legend/_3_946.png" /> רמת הגולן<br />\
    <img src="styles/legend/_3_947.png" /> רמת הכובש<br />\
    <img src="styles/legend/_3_948.png" /> רמת הנגב<br />\
    <img src="styles/legend/_3_949.png" /> רמת השופט<br />\
    <img src="styles/legend/_3_950.png" /> רמת השרון<br />\
    <img src="styles/legend/_3_951.png" /> רמת חובב<br />\
    <img src="styles/legend/_3_952.png" /> רמת יוחנן<br />\
    <img src="styles/legend/_3_953.png" /> רמת ישי<br />\
    <img src="styles/legend/_3_954.png" /> רמת מגשימים<br />\
    <img src="styles/legend/_3_955.png" /> רמת רזיאל<br />\
    <img src="styles/legend/_3_956.png" /> רמת רחל<br />\
    <img src="styles/legend/_3_957.png" /> רעים<br />\
    <img src="styles/legend/_3_958.png" /> רעננה<br />\
    <img src="styles/legend/_3_959.png" /> רקפת<br />\
    <img src="styles/legend/_3_960.png" /> רשפון<br />\
    <img src="styles/legend/_3_961.png" /> רשפים<br />\
    <img src="styles/legend/_3_962.png" /> רתמים<br />\
    <img src="styles/legend/_3_963.png" /> שבי שומרון<br />\
    <img src="styles/legend/_3_964.png" /> שגב<br />\
    <img src="styles/legend/_3_965.png" /> שגב שלום<br />\
    <img src="styles/legend/_3_966.png" /> שגב-שלום<br />\
    <img src="styles/legend/_3_967.png" /> שדה אליהו<br />\
    <img src="styles/legend/_3_968.png" /> שדה אליעזר<br />\
    <img src="styles/legend/_3_969.png" /> שדה בוקר<br />\
    <img src="styles/legend/_3_970.png" /> שדה יואב<br />\
    <img src="styles/legend/_3_971.png" /> שדה משה<br />\
    <img src="styles/legend/_3_972.png" /> שדה צבי<br />\
    <img src="styles/legend/_3_973.png" /> שדות ים<br />\
    <img src="styles/legend/_3_974.png" /> שדות מיכה<br />\
    <img src="styles/legend/_3_975.png" /> שדות נגב<br />\
    <img src="styles/legend/_3_976.png" /> שדי תרומות<br />\
    <img src="styles/legend/_3_977.png" /> שדמה<br />\
    <img src="styles/legend/_3_978.png" /> שדמות מחולה<br />\
    <img src="styles/legend/_3_979.png" /> שדרות<br />\
    <img src="styles/legend/_3_980.png" /> שהם<br />\
    <img src="styles/legend/_3_981.png" /> שואבה<br />\
    <img src="styles/legend/_3_982.png" /> שובל<br />\
    <img src="styles/legend/_3_983.png" /> שוהם<br />\
    <img src="styles/legend/_3_984.png" /> שומרה<br />\
    <img src="styles/legend/_3_985.png" /> שומרון<br />\
    <img src="styles/legend/_3_986.png" /> שומריה<br />\
    <img src="styles/legend/_3_987.png" /> שורש<br />\
    <img src="styles/legend/_3_988.png" /> שזור<br />\
    <img src="styles/legend/_3_989.png" /> שחרות<br />\
    <img src="styles/legend/_3_990.png" /> שטח ללא שיפוט<br />\
    <img src="styles/legend/_3_991.png" /> שיבולים<br />\
    <img src="styles/legend/_3_992.png" /> שיבטה<br />\
    <img src="styles/legend/_3_993.png" /> שיזפון<br />\
    <img src="styles/legend/_3_994.png" /> שיטים<br />\
    <img src="styles/legend/_3_995.png" /> שילה<br />\
    <img src="styles/legend/_3_996.png" /> שילת<br />\
    <img src="styles/legend/_3_997.png" /> שלווה<br />\
    <img src="styles/legend/_3_998.png" /> שלוחות<br />\
    <img src="styles/legend/_3_999.png" /> שלומי<br />\
    <img src="styles/legend/_3_1000.png" /> שמיר<br />\
    <img src="styles/legend/_3_1001.png" /> שמעה<br />\
    <img src="styles/legend/_3_1002.png" /> שמרת<br />\
    <img src="styles/legend/_3_1003.png" /> שניר<br />\
    <img src="styles/legend/_3_1004.png" /> שעל<br />\
    <img src="styles/legend/_3_1005.png" /> שעלבים<br />\
    <img src="styles/legend/_3_1006.png" /> שער הגולן<br />\
    <img src="styles/legend/_3_1007.png" /> שער הנגב<br />\
    <img src="styles/legend/_3_1008.png" /> שער העמקים<br />\
    <img src="styles/legend/_3_1009.png" /> שערי תקוה<br />\
    <img src="styles/legend/_3_1010.png" /> שערי תקווה<br />\
    <img src="styles/legend/_3_1011.png" /> שערייה<br />\
    <img src="styles/legend/_3_1012.png" /> שפיים<br />\
    <img src="styles/legend/_3_1013.png" /> שפיר<br />\
    <img src="styles/legend/_3_1014.png" /> שפרעם<br />\
    <img src="styles/legend/_3_1015.png" /> שקד<br />\
    <img src="styles/legend/_3_1016.png" /> שקף<br />\
    <img src="styles/legend/_3_1017.png" /> שרונה<br />\
    <img src="styles/legend/_3_1018.png" /> שריד<br />\
    <img src="styles/legend/_3_1019.png" /> שתולה<br />\
    <img src="styles/legend/_3_1020.png" /> שתולים<br />\
    <img src="styles/legend/_3_1021.png" /> תדהר<br />\
    <img src="styles/legend/_3_1022.png" /> תובל<br />\
    <img src="styles/legend/_3_1023.png" /> תומר<br />\
    <img src="styles/legend/_3_1024.png" /> תורען<br />\
    <img src="styles/legend/_3_1025.png" /> תימורים<br />\
    <img src="styles/legend/_3_1026.png" /> תל אביב<br />\
    <img src="styles/legend/_3_1027.png" /> תל אביב -יפו<br />\
    <img src="styles/legend/_3_1028.png" /> תל אביב יפו<br />\
    <img src="styles/legend/_3_1029.png" /> תל אביביפו<br />\
    <img src="styles/legend/_3_1030.png" /> תל דן<br />\
    <img src="styles/legend/_3_1031.png" /> תל השומר<br />\
    <img src="styles/legend/_3_1032.png" /> תל יוסף<br />\
    <img src="styles/legend/_3_1033.png" /> תל יצחק<br />\
    <img src="styles/legend/_3_1034.png" /> תל מונד<br />\
    <img src="styles/legend/_3_1035.png" /> תל קציר<br />\
    <img src="styles/legend/_3_1036.png" /> תל שבע<br />\
    <img src="styles/legend/_3_1037.png" /> תלם<br />\
    <img src="styles/legend/_3_1038.png" /> תלמי אליהו<br />\
    <img src="styles/legend/_3_1039.png" /> תלמי אלעזר<br />\
    <img src="styles/legend/_3_1040.png" /> תלמי ביל``ו<br />\
    <img src="styles/legend/_3_1041.png" /> תמר<br />\
    <img src="styles/legend/_3_1042.png" /> תמרה<br />\
    <img src="styles/legend/_3_1043.png" /> תמרת<br />\
    <img src="styles/legend/_3_1044.png" /> תעוז<br />\
    <img src="styles/legend/_3_1045.png" /> תפן<br />\
    <img src="styles/legend/_3_1046.png" /> תפרח<br />\
    <img src="styles/legend/_3_1047.png" /> תקומה<br />\
    <img src="styles/legend/_3_1048.png" /> תקוע<br />\
    <img src="styles/legend/_3_1049.png" /> תרום<br />\
    <img src="styles/legend/_3_1050.png" /> <br />'
        });

lyr_OSMStandard_0.setVisible(true);lyr__1.setVisible(true);lyr__2.setVisible(true);lyr__3.setVisible(true);
var layersList = [lyr_OSMStandard_0,lyr__1,lyr__2,lyr__3];
lyr__1.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ID': 'ID', 'company': 'company', 'site_num': 'site_num', 'city': 'city', 'address': 'address', 'local_auth': 'local_auth', 'shiput': 'shiput', 'X': 'X', 'Y': 'Y', 'type_': 'type_', 'hakama_dat': 'hakama_dat', 'hafala_dat': 'hafala_dat', 'last_bedik': 'last_bedik', 'permit': 'permit', 'max_intens': 'max_intens', 'hakama_fil': 'hakama_fil', 'hafala_fil': 'hafala_fil', 'intensity': 'intensity', 'percent_': 'percent_', });
lyr__2.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ID': 'ID', 'company': 'company', 'site_num': 'site_num', 'city': 'city', 'address': 'address', 'local_auth': 'local_auth', 'shiput': 'shiput', 'X': 'X', 'Y': 'Y', 'type_': 'type_', 'hakama_dat': 'hakama_dat', 'hafala_dat': 'hafala_dat', 'last_bedik': 'last_bedik', 'permit': 'permit', 'max_intens': 'max_intens', 'hakama_fil': 'hakama_fil', 'hafala_fil': 'hafala_fil', 'intensity': 'intensity', 'percent_': 'percent_', });
lyr__3.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ID': 'ID', 'company': 'company', 'site_num': 'site_num', 'city': 'city', 'address': 'address', 'local_auth': 'local_auth', 'shiput': 'shiput', 'X': 'X', 'Y': 'Y', 'type_': 'type_', 'hakama_dat': 'hakama_dat', 'hafala_dat': 'hafala_dat', 'last_bedik': 'last_bedik', 'permit': 'permit', 'max_intens': 'max_intens', 'hakama_fil': 'hakama_fil', 'hafala_fil': 'hafala_fil', 'intensity': 'intensity', 'percent_': 'percent_', });
lyr__1.set('fieldImages', {'OBJECTID': 'TextEdit', 'ID': 'TextEdit', 'company': 'TextEdit', 'site_num': 'TextEdit', 'city': 'TextEdit', 'address': 'TextEdit', 'local_auth': 'TextEdit', 'shiput': 'TextEdit', 'X': 'TextEdit', 'Y': 'TextEdit', 'type_': 'TextEdit', 'hakama_dat': 'DateTime', 'hafala_dat': 'DateTime', 'last_bedik': 'DateTime', 'permit': 'TextEdit', 'max_intens': 'TextEdit', 'hakama_fil': 'TextEdit', 'hafala_fil': 'TextEdit', 'intensity': 'TextEdit', 'percent_': 'TextEdit', });
lyr__2.set('fieldImages', {'OBJECTID': 'TextEdit', 'ID': 'TextEdit', 'company': 'TextEdit', 'site_num': 'TextEdit', 'city': 'TextEdit', 'address': 'TextEdit', 'local_auth': 'TextEdit', 'shiput': 'TextEdit', 'X': 'TextEdit', 'Y': 'TextEdit', 'type_': 'TextEdit', 'hakama_dat': 'DateTime', 'hafala_dat': 'DateTime', 'last_bedik': 'DateTime', 'permit': 'TextEdit', 'max_intens': 'TextEdit', 'hakama_fil': 'TextEdit', 'hafala_fil': 'TextEdit', 'intensity': 'TextEdit', 'percent_': 'TextEdit', });
lyr__3.set('fieldImages', {'OBJECTID': 'TextEdit', 'ID': 'TextEdit', 'company': 'TextEdit', 'site_num': 'TextEdit', 'city': 'TextEdit', 'address': 'TextEdit', 'local_auth': 'TextEdit', 'shiput': 'TextEdit', 'X': 'TextEdit', 'Y': 'TextEdit', 'type_': 'TextEdit', 'hakama_dat': 'DateTime', 'hafala_dat': 'DateTime', 'last_bedik': 'DateTime', 'permit': 'TextEdit', 'max_intens': 'TextEdit', 'hakama_fil': 'TextEdit', 'hafala_fil': 'TextEdit', 'intensity': 'TextEdit', 'percent_': 'TextEdit', });
lyr__1.set('fieldLabels', {'OBJECTID': 'no label', 'ID': 'no label', 'company': 'no label', 'site_num': 'no label', 'city': 'no label', 'address': 'no label', 'local_auth': 'no label', 'shiput': 'no label', 'X': 'no label', 'Y': 'no label', 'type_': 'no label', 'hakama_dat': 'no label', 'hafala_dat': 'no label', 'last_bedik': 'no label', 'permit': 'no label', 'max_intens': 'no label', 'hakama_fil': 'no label', 'hafala_fil': 'no label', 'intensity': 'no label', 'percent_': 'no label', });
lyr__2.set('fieldLabels', {'OBJECTID': 'no label', 'ID': 'no label', 'company': 'no label', 'site_num': 'no label', 'city': 'no label', 'address': 'no label', 'local_auth': 'no label', 'shiput': 'no label', 'X': 'no label', 'Y': 'no label', 'type_': 'no label', 'hakama_dat': 'no label', 'hafala_dat': 'no label', 'last_bedik': 'no label', 'permit': 'no label', 'max_intens': 'no label', 'hakama_fil': 'no label', 'hafala_fil': 'no label', 'intensity': 'no label', 'percent_': 'no label', });
lyr__3.set('fieldLabels', {'OBJECTID': 'no label', 'ID': 'no label', 'company': 'no label', 'site_num': 'no label', 'city': 'no label', 'address': 'no label', 'local_auth': 'no label', 'shiput': 'no label', 'X': 'no label', 'Y': 'no label', 'type_': 'no label', 'hakama_dat': 'no label', 'hafala_dat': 'no label', 'last_bedik': 'no label', 'permit': 'no label', 'max_intens': 'no label', 'hakama_fil': 'no label', 'hafala_fil': 'no label', 'intensity': 'no label', 'percent_': 'no label', });
lyr__3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});